trigger:
  - main  # Trigger pipeline on changes to the 'main' branch

pool:
  name: Lab4-Self-Hosted  # Specify your self-hosted agent pool

steps:
  # Step 1: Install .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'  # Ensure you're using .NET 8.x as required

  # Step 2: Restore NuGet Packages
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # Step 3: Build the Project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'

  # Step 4: Pack the Project into a NuGet Package
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

  # Step 5: Push the NuGet Package to Azure Artifacts
  - task: NuGetCommand@2
    inputs:
     command: 'push'
     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
     feedsToUse: 'select'
     publishVstsFeed: 'StringExtensionsFeed' # Replace with your actual feed name
     allowPackageConflicts: true
    
